# Data Cleaning and Manipulation

## Import necessary libraries and packages

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## GDP Deflator Dataset Cleaning

In [6]:
# First, we import DGDP dataset which was downloaded from the link: https://databank.worldbank.org/reports.aspx?source=2&series=NY.GDP.DEFL.ZS&country=#
dgdp = pd.read_csv("/content/dgdp.csv")
dgdp.head()

,Series Name,Series Code,Country Name,Country Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Austria,AUT,69.989256,71.345147,72.132951,73.046877,74.309100,76.190582,...,84.700919,86.472578,87.950155,89.715090,91.771929,93.437361,94.348672,96.056836,97.472411,100.0
1,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Belgium,BEL,70.707905,72.109914,73.292516,74.648512,76.078023,77.662784,...,86.500821,88.408801,89.657566,90.411044,91.425310,93.158084,95.005561,96.637075,98.428959,100.0
2,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Canada,CAN,68.992087,70.077799,70.959044,73.265026,75.654106,78.011971,...,89.156284,90.242603,91.813490,93.595773,92.783688,93.448927,95.851512,97.434134,98.940535,100.0
3,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Czechia,CZE,65.854994,69.104660,71.039781,72.043205,74.966077,75.054388,...,81.377883,82.471106,83.519798,85.780442,86.839433,88.134412,89.618261,92.139545,95.678918,100.0
4,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Estonia,EST,42.025917,44.904154,47.061294,48.891690,51.184445,54.216558,...,75.885563,79.076953,82.338050,84.690072,85.796496,87.888667,91.176668,95.597893,99.252294,100.0

In [7]:
# Next, we rename the year columns to make them look cleaner
new_cols = {}
for col in dgdp.columns:
    if '[' in col and 'YR' in col:
        # extract year before space
        year = col.split()[0]
        new_cols[col] = year
dgdp = dgdp.rename(columns=new_cols)
dgdp.head()

,Series Name,Series Code,Country Name,Country Code,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Austria,AUT,69.989256,71.345147,72.132951,73.046877,74.309100,76.190582,...,84.700919,86.472578,87.950155,89.715090,91.771929,93.437361,94.348672,96.056836,97.472411,100.0
1,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Belgium,BEL,70.707905,72.109914,73.292516,74.648512,76.078023,77.662784,...,86.500821,88.408801,89.657566,90.411044,91.425310,93.158084,95.005561,96.637075,98.428959,100.0
2,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Canada,CAN,68.992087,70.077799,70.959044,73.265026,75.654106,78.011971,...,89.156284,90.242603,91.813490,93.595773,92.783688,93.448927,95.851512,97.434134,98.940535,100.0
3,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Czechia,CZE,65.854994,69.104660,71.039781,72.043205,74.966077,75.054388,...,81.377883,82.471106,83.519798,85.780442,86.839433,88.134412,89.618261,92.139545,95.678918,100.0
4,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Estonia,EST,42.025917,44.904154,47.061294,48.891690,51.184445,54.216558,...,75.885563,79.076953,82.338050,84.690072,85.796496,87.888667,91.176668,95.597893,99.252294,100.0

In [8]:
# Next, we rebase GDP deflator to 2015
dgdp2 = dgdp.iloc[:-5,:]
multipliers = 100 / dgdp2['2015']
for i in dgdp2.iloc[:,4:].columns:
  dgdp2.loc[:,i] = dgdp2.loc[:,i]*multipliers

dgdp2.head()

,Series Name,Series Code,Country Name,Country Code,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Austria,AUT,76.264340,77.741797,78.600234,79.596101,80.971491,83.021664,...,92.295019,94.225521,95.835574,97.758749,100.0,101.814751,102.807768,104.669082,106.211575,108.965782
1,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Belgium,BEL,77.339530,78.873032,80.166549,81.649723,83.213306,84.946700,...,94.613647,96.700575,98.066461,98.890607,100.0,101.895289,103.916039,105.700571,107.660514,109.378902
2,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Canada,CAN,74.357991,75.528146,76.477930,78.963262,81.538154,84.079404,...,96.090472,97.261281,98.954345,100.875245,100.0,100.716978,103.306426,105.012138,106.635700,107.777566
3,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Czechia,CZE,75.835357,79.577511,81.805902,82.961395,86.327230,86.428925,...,93.710750,94.969650,96.177273,98.780518,100.0,101.491234,103.199961,106.103347,110.179114,115.155059
4,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,Estonia,EST,48.983255,52.337981,54.852233,56.985648,59.657967,63.192042,...,88.448324,92.168045,95.969012,98.710409,100.0,102.438527,106.270853,111.424006,115.683389,116.554876

In [9]:
# Finally, we transform the wide dataframe to the long format for easier future use:
dgdp_clean = dgdp2.iloc[:,2:].melt(id_vars={'Country Name', 'Country Code'}, var_name= 'year', value_name= 'dgdp')
dgdp_clean = dgdp_clean.rename(columns = {'Country Name': 'country', 'Country Code': 'country_code'})
dgdp_clean['year'] = dgdp_clean['year'].astype(int)
dgdp_clean

             country country_code  year        dgdp
0            Austria          AUT  2000   76.264340
1            Belgium          BEL  2000   77.339530
2             Canada          CAN  2000   74.357991
3            Czechia          CZE  2000   75.835357
4            Estonia          EST  2000   48.983255
..               ...          ...   ...         ...
436  Slovak Republic          SVK  2020  107.920076
437         Slovenia          SVN  2020  108.125978
438           Sweden          SWE  2020  111.174090
439    United States          USA  2020  108.266880
440   United Kingdom          GBR  2020  113.480926

[441 rows x 4 columns]

## Purchasing Power Parities Dataset Cleaning

In [10]:
# First, we import the PPP dataset downloaded from: https://data-explorer.oecd.org/vis?tm=Purchasing%20Power%20Parities&pg=0&snb=37&vw=tb&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_NAMAIN10%40DF_TABLE4&df[ag]=OECD.SDD.NAD&df[vs]=2.0&dq=A.AUT%2BBEL%2BCAN%2BCZE%2BEST%2BFIN%2BFRA%2BGRC%2BIRL%2BITA%2BJPN%2BLVA%2BLTU%2BLUX%2BNLD%2BNOR%2BSVK%2BSVN%2BSWE%2BGBR%2BUSA...PPP_B1GQ.......&pd=2015%2C2015&to[TIME_PERIOD]=false
ppp = pd.read_csv("/content/ppp.csv")
ppp.head()

# This dataset is PPP for 21 research countries in 2015

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency of observation,REF_AREA,Reference area,SECTOR,Institutional sector,...,CONF_STATUS,Confidentiality status,DECIMALS,Decimals,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,CURRENCY,Currency
0,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE4(2.0),Annual Purchasing Power Parities and exchange ...,I,A,Annual,USA,United States,S1,Total economy,...,F,Free (free for publication),6,Six,A,Normal value,0,Units,USD,US dollar
1,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE4(2.0),Annual Purchasing Power Parities and exchange ...,I,A,Annual,CAN,Canada,S1,Total economy,...,F,Free (free for publication),6,Six,A,Normal value,0,Units,CAD,Canadian dollar
2,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE4(2.0),Annual Purchasing Power Parities and exchange ...,I,A,Annual,CZE,Czechia,S1,Total economy,...,F,Free (free for publication),6,Six,A,Normal value,0,Units,CZK,Czech koruna
3,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE4(2.0),Annual Purchasing Power Parities and exchange ...,I,A,Annual,JPN,Japan,S1,Total economy,...,F,Free (free for publication),6,Six,A,Normal value,0,Units,JPY,Yen
4,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE4(2.0),Annual Purchasing Power Parities and exchange ...,I,A,Annual,NOR,Norway,S1,Total economy,...,F,Free (free for publication),6,Six,A,Normal value,0,Units,NOK,Norwegian krone

In [11]:
# Next, we select and rename the necessary columns:
ppp = ppp[['REF_AREA', 'Reference area', 'OBS_VALUE']]
ppp_clean = ppp.rename(columns = {'REF_AREA' : 'country_code', 'Reference area': 'country', 'OBS_VALUE': 'ppp'})
ppp_clean

   country_code          country         ppp
0           USA    United States    1.000000
1           CAN           Canada    1.248004
2           CZE          Czechia   12.934509
3           JPN            Japan  103.449739
4           NOR           Norway    9.929852
5           SWE           Sweden    8.852008
6           GBR   United Kingdom    0.692365
7           AUT          Austria    0.798599
8           BEL          Belgium    0.799784
9           EST          Estonia    0.537436
10          FIN          Finland    0.907504
11          FRA           France    0.808478
12          GRC           Greece    0.608907
13          IRL          Ireland    0.809469
14          ITA            Italy    0.738495
15          LVA           Latvia    0.497436
16          LTU        Lithuania    0.445738
17          LUX       Luxembourg    0.881025
18          NLD      Netherlands    0.809761
19          SVK  Slovak Republic    0.491417
20          SVN         Slovenia    0.595138

## GTFP's Variable's Datasets Cleaning (No CO2)

### VA (Value added) and IC (Intermediate consumption) Cleaning

In [12]:
# First, we import VA and IC dataset, which was downloaded from: https://data-explorer.oecd.org/vis?snb=1&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_STAN%40DF_STAN_2025&df[ag]=OECD.STI.PIE&df[vs]=1.0&dq=A.AUT%2BBEL%2BCAN%2BCZE%2BEST%2BFIN%2BFRA%2BGRC%2BIRL%2BITA%2BJPN%2BLVA%2BLTU%2BLUX%2BNLD%2BNOR%2BSVK%2BSVN%2BSWE%2BGBR%2BUSA.A%2BGTU%2BC.P2%2BB1G.V.XDC&pd=2000%2C2020&to[TIME_PERIOD]=false&ly[cl]=TIME_PERIOD&ly[rw]=ACTIVITY&lc=en&pg=0&vw=ov&lb=bt
ic_va = pd.read_csv("/content/ic_va.csv")
ic_va.head()

# Next, we select and rename necessary columns:
ic_va_clean = ic_va[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
ic_va_clean

,REF_AREA,Reference area,Economic activity,Measure,TIME_PERIOD,OBS_VALUE
0,SWE,Sweden,Manufacturing,Intermediate consumption,2019,1.452462e+06
1,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2008,1.156000e+05
2,SWE,Sweden,Manufacturing,Intermediate consumption,2008,1.313873e+06
3,AUT,Austria,Manufacturing,Value added,2017,6.406617e+04
4,AUT,Austria,Manufacturing,Intermediate consumption,2017,1.248287e+05
...,...,...,...,...,...,...
2641,SWE,Sweden,Services,Intermediate consumption,2005,1.367598e+06
2642,SWE,Sweden,Services,Value added,2005,1.837320e+06
2643,SWE,Sweden,Services,Intermediate consumption,2011,1.868757e+06
2644,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2019,1.217320e+05
2645,SWE,Sweden,Services,Value added,2011,2.348793e+06

In [13]:
# Next, we select and rename necessary columns:
ic_va_clean = ic_va[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
ic_va_clean.head()

,REF_AREA,Reference area,Economic activity,Measure,TIME_PERIOD,OBS_VALUE
0,SWE,Sweden,Manufacturing,Intermediate consumption,2019,1.452462e+06
1,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2008,1.156000e+05
2,SWE,Sweden,Manufacturing,Intermediate consumption,2008,1.313873e+06
3,AUT,Austria,Manufacturing,Value added,2017,6.406617e+04
4,AUT,Austria,Manufacturing,Intermediate consumption,2017,1.248287e+05

### K (Net capital stock) and ICT (ICT Net capital stock) Datasets Cleaning

In [14]:
# First, we import k and ict dataset, which was downloaded from: https://data-explorer.oecd.org/vis?snb=1&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_STAN%40DF_STAN_2025&df[ag]=OECD.STI.PIE&df[vs]=1.0&dq=A.AUT%2BBEL%2BCAN%2BCZE%2BEST%2BFIN%2BFRA%2BGRC%2BIRL%2BITA%2BJPN%2BLVA%2BLTU%2BLUX%2BNLD%2BNOR%2BSVK%2BSVN%2BSWE%2BGBR%2BUSA.A%2BGTU%2BC.N11NA%2BN11NA_ICT.U.&pd=2000%2C2020&to[TIME_PERIOD]=false&ly[cl]=TIME_PERIOD&ly[rw]=ACTIVITY&lc=en&pg=0&vw=ov&lb=bt
k_ict = pd.read_csv("/content/k_ict.csv")
k_ict

# Next, we select and rename necessary columns:
k_ict_clean = k_ict[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
k_ict_clean

,REF_AREA,Reference area,Economic activity,Measure,TIME_PERIOD,OBS_VALUE
0,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2018,4.488720e+05
1,SWE,Sweden,Manufacturing,Net capital stock,2003,9.558740e+05
2,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2003,2.420750e+05
3,AUT,Austria,Manufacturing,"Net capital stock, ICT equipment, software and...",2002,2.588958e+03
4,AUT,Austria,"Agriculture, forestry and fishing","Net capital stock, ICT equipment, software and...",2018,1.149926e+02
...,...,...,...,...,...,...
2641,SVN,Slovenia,Services,Net capital stock,2000,4.180670e+04
2642,SVN,Slovenia,Services,Net capital stock,2018,1.042729e+05
2643,SVN,Slovenia,Services,Net capital stock,2013,9.673620e+04
2644,SWE,Sweden,Manufacturing,Net capital stock,2018,1.251960e+06
2645,SVN,Slovenia,Services,Net capital stock,2010,9.032180e+04

In [15]:
# Next, we select and rename necessary columns:
k_ict_clean = k_ict[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
k_ict_clean.head()

,REF_AREA,Reference area,Economic activity,Measure,TIME_PERIOD,OBS_VALUE
0,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2018,448872.000000
1,SWE,Sweden,Manufacturing,Net capital stock,2003,955874.000000
2,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2003,242075.000000
3,AUT,Austria,Manufacturing,"Net capital stock, ICT equipment, software and...",2002,2588.958166
4,AUT,Austria,"Agriculture, forestry and fishing","Net capital stock, ICT equipment, software and...",2018,114.992603

### L (labor) Dataset Cleaning

In [16]:
# First, we import the labor dataset, which was downloaded from: https://data-explorer.oecd.org/vis?snb=1&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_STAN%40DF_STAN_2025&df[ag]=OECD.STI.PIE&df[vs]=1.0&dq=A.AUT%2BBEL%2BCAN%2BCZE%2BEST%2BFIN%2BFRA%2BGRC%2BIRL%2BITA%2BJPN%2BLVA%2BLTU%2BLUX%2BNLD%2BNOR%2BSVK%2BSVN%2BSWE%2BGBR%2BUSA.A%2BGTU%2BC.EMP..PS&pd=2000%2C2020&to[TIME_PERIOD]=false&ly[cl]=TIME_PERIOD&ly[rw]=ACTIVITY&lc=en&pg=0&vw=ov&lb=bt
l = pd.read_csv("/content/l.csv")

# Next, we select and rename necessary columns:
l_clean = l[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
l_clean = l_clean.rename(columns = {'REF_AREA' : 'country_code', 'Reference area': 'country',
                              'TIME_PERIOD': 'year'})
l_clean

,country_code,country,Economic activity,Measure,year,OBS_VALUE
0,GBR,United Kingdom,"Agriculture, forestry and fishing",Total employment,2016,396.312
1,GBR,United Kingdom,Manufacturing,Total employment,2016,2495.132
2,USA,United States,"Agriculture, forestry and fishing",Total employment,2016,2269.000
3,USA,United States,Manufacturing,Total employment,2016,12646.000
4,SVN,Slovenia,"Agriculture, forestry and fishing",Total employment,2000,106.700
...,...,...,...,...,...,...
1318,SVK,Slovak Republic,Services,Total employment,2020,1584.180
1319,SVN,Slovenia,Services,Total employment,2020,654.300
1320,SWE,Sweden,Services,Total employment,2020,4024.800
1321,GBR,United Kingdom,Services,Total employment,2020,27042.965
1322,USA,United States,Services,Total employment,2020,132206.000

In [17]:
# Next, we select and rename necessary columns:
l_clean = l[['REF_AREA', 'Reference area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
l_clean = l_clean.rename(columns = {'REF_AREA' : 'country_code', 'Reference area': 'country',
                              'TIME_PERIOD': 'year'})
l_clean.head()

,country_code,country,Economic activity,Measure,year,OBS_VALUE
0,GBR,United Kingdom,"Agriculture, forestry and fishing",Total employment,2016,396.312
1,GBR,United Kingdom,Manufacturing,Total employment,2016,2495.132
2,USA,United States,"Agriculture, forestry and fishing",Total employment,2016,2269.000
3,USA,United States,Manufacturing,Total employment,2016,12646.000
4,SVN,Slovenia,"Agriculture, forestry and fishing",Total employment,2000,106.700

## GTFP'S VARIABLES' DATASETS APPENDING (No CO2)

In [18]:
# In this step, we will append all the clean datasets except l_clean
appended_df = pd.concat([k_ict_clean, ic_va_clean])

# we rename the columns for easier future use:
appended_df = appended_df.rename(columns = {'REF_AREA' : 'country_code', 'Reference area': 'country',
                              'TIME_PERIOD': 'year'})

appended_df

,country_code,country,Economic activity,Measure,year,OBS_VALUE
0,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2018,4.488720e+05
1,SWE,Sweden,Manufacturing,Net capital stock,2003,9.558740e+05
2,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2003,2.420750e+05
3,AUT,Austria,Manufacturing,"Net capital stock, ICT equipment, software and...",2002,2.588958e+03
4,AUT,Austria,"Agriculture, forestry and fishing","Net capital stock, ICT equipment, software and...",2018,1.149926e+02
...,...,...,...,...,...,...
2641,SWE,Sweden,Services,Intermediate consumption,2005,1.367598e+06
2642,SWE,Sweden,Services,Value added,2005,1.837320e+06
2643,SWE,Sweden,Services,Intermediate consumption,2011,1.868757e+06
2644,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2019,1.217320e+05
2645,SWE,Sweden,Services,Value added,2011,2.348793e+06

In [19]:
# However, the dataset above is not converted to 2015 constant USD yet.
# To do that, we first merge the appended dataframe with the clean PPP and DGDP datasets:

appended_df2 = appended_df.merge(ppp_clean, on = ['country_code', 'country']).merge(dgdp_clean,
                                                                                    on = ['country_code', 'country', 'year'])

# The code below convert OBS_VALUE to 2015 constant USD OBS_VALUE
appended_df2['OBS_VALUE'] = appended_df2['OBS_VALUE']* 100 / (appended_df2['ppp']*appended_df2['dgdp'])
appended_df2

,country_code,country,Economic activity,Measure,year,OBS_VALUE,ppp,dgdp
0,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2018,47553.819408,8.852008,106.633905
1,SWE,Sweden,Manufacturing,Net capital stock,2003,131310.875549,8.852008,82.235276
2,SWE,Sweden,"Agriculture, forestry and fishing",Net capital stock,2003,33254.466801,8.852008,82.235276
3,AUT,Austria,Manufacturing,"Net capital stock, ICT equipment, software and...",2002,4124.510675,0.798599,78.600234
4,AUT,Austria,"Agriculture, forestry and fishing","Net capital stock, ICT equipment, software and...",2018,137.569680,0.798599,104.669082
...,...,...,...,...,...,...,...,...
5287,SWE,Sweden,Services,Intermediate consumption,2005,185675.302167,8.852008,83.207509
5288,SWE,Sweden,Services,Value added,2005,249448.263435,8.852008,83.207509
5289,SWE,Sweden,Services,Intermediate consumption,2011,224156.801888,8.852008,94.180093
5290,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2019,12591.576778,8.852008,109.215139
5291,SWE,Sweden,Services,Value added,2011,281736.965896,8.852008,94.180093

In [20]:
# Next, we append with the l_clean dataset:
appended_clean = pd.concat([l_clean, appended_df2.iloc[:,:-2]])
appended_clean

,country_code,country,Economic activity,Measure,year,OBS_VALUE
0,GBR,United Kingdom,"Agriculture, forestry and fishing",Total employment,2016,396.312000
1,GBR,United Kingdom,Manufacturing,Total employment,2016,2495.132000
2,USA,United States,"Agriculture, forestry and fishing",Total employment,2016,2269.000000
3,USA,United States,Manufacturing,Total employment,2016,12646.000000
4,SVN,Slovenia,"Agriculture, forestry and fishing",Total employment,2000,106.700000
...,...,...,...,...,...,...
5287,SWE,Sweden,Services,Intermediate consumption,2005,185675.302167
5288,SWE,Sweden,Services,Value added,2005,249448.263435
5289,SWE,Sweden,Services,Intermediate consumption,2011,224156.801888
5290,SWE,Sweden,"Agriculture, forestry and fishing",Intermediate consumption,2019,12591.576778
5291,SWE,Sweden,Services,Value added,2011,281736.965896

## CO2 Dataset Cleaning

In [21]:
# First , we import the CO2 dataset, which was downloaded from the link: https://data-explorer.oecd.org/vis?tm=DF_ICIO_GHG_EXPD_2023&snb=5&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_ICIO_GHG_SCOPE%2540DF_ICIO_GHG_SCOPE_2023&df[ag]=OECD.STI.PIE&df[vs]=1.0&dq=A.SCOPE_GHG.AUT%2BBEL%2BCAN%2BCZE%2BEST%2BFIN%2BFRA%2BGRC%2BIRL%2BITA%2BJPN%2BLVA%2BLTU%2BLUX%2BNLD%2BNOR%2BSVK%2BSVN%2BSWE%2BGBR%2BUSA.A01_02%2BA03%2BG%2BH49%2BH50%2BH51%2BH52%2BO%2BN%2BM%2BL%2BK%2BJ62_63%2BJ61%2BJ58T60%2BI%2BH53%2BP%2BQ%2BR%2BS%2BT%2BC10T12%2BC13T15%2BC16%2BC17_18%2BC19%2BC20%2BC21%2BC22%2BC23%2BC24%2BC25%2BC26%2BC27%2BC28%2BC29%2BC30%2BC31T33._T.&pd=2000%2C2020&to[TIME_PERIOD]=false&vw=ov&lb=bt
co2 = pd.read_csv("/content/co2.csv")

# Next, we select necessary columns:
co2 = co2[['EMISSIONS_ORIGIN_AREA', 'Emissions origin area', 'ACTIVITY', 'Economic activity', 'TIME_PERIOD', 'OBS_VALUE']]
co2

,EMISSIONS_ORIGIN_AREA,Emissions origin area,ACTIVITY,Economic activity,TIME_PERIOD,OBS_VALUE
0,LUX,Luxembourg,C19,Manufacture of coke and refined petroleum prod...,2000,0.000
1,LUX,Luxembourg,A03,Fishing and aquaculture,2000,0.000
2,LUX,Luxembourg,A03,Fishing and aquaculture,2001,0.000
3,LUX,Luxembourg,C19,Manufacture of coke and refined petroleum prod...,2001,0.000
4,LUX,Luxembourg,C19,Manufacture of coke and refined petroleum prod...,2002,0.000
...,...,...,...,...,...,...
17194,LVA,Latvia,H52,Warehousing and support activities for transpo...,2000,2.138
17195,SWE,Sweden,H52,Warehousing and support activities for transpo...,2000,8.395
17196,LTU,Lithuania,H52,Warehousing and support activities for transpo...,2000,0.344
17197,USA,United States,H52,Warehousing and support activities for transpo...,2000,43.541
17198,AUT,Austria,H52,Warehousing and support activities for transpo...,2000,0.685

In [22]:
# After that, we classify the activities into 3 main industries:
co2['Economic activity'] = co2['ACTIVITY'].str[0].map({
    'A': 'Agriculture, forestry and fishing',
    'C': 'Manufacturing'
}).fillna('Services')
co2

,EMISSIONS_ORIGIN_AREA,Emissions origin area,ACTIVITY,Economic activity,TIME_PERIOD,OBS_VALUE
0,LUX,Luxembourg,C19,Manufacturing,2000,0.000
1,LUX,Luxembourg,A03,"Agriculture, forestry and fishing",2000,0.000
2,LUX,Luxembourg,A03,"Agriculture, forestry and fishing",2001,0.000
3,LUX,Luxembourg,C19,Manufacturing,2001,0.000
4,LUX,Luxembourg,C19,Manufacturing,2002,0.000
...,...,...,...,...,...,...
17194,LVA,Latvia,H52,Services,2000,2.138
17195,SWE,Sweden,H52,Services,2000,8.395
17196,LTU,Lithuania,H52,Services,2000,0.344
17197,USA,United States,H52,Services,2000,43.541
17198,AUT,Austria,H52,Services,2000,0.685

In [23]:
# Next, we calculate the aggregated total of CO2 emissions:
co2 = co2.groupby(['EMISSIONS_ORIGIN_AREA',	'Emissions origin area', 'Economic activity', 'TIME_PERIOD'])['OBS_VALUE'].sum().reset_index()
co2['Measure'] = 'co2'
co2_clean = co2[['EMISSIONS_ORIGIN_AREA',	'Emissions origin area', 'Economic activity', 'Measure', 'TIME_PERIOD', 'OBS_VALUE']]
co2_clean = co2_clean.rename(columns = {'EMISSIONS_ORIGIN_AREA' : 'country_code', 'Emissions origin area': 'country', 'TIME_PERIOD': 'year'})

# Finally, we multiply the OBS_VALUE by 1000 to convert it to thousands tonnes of CO2 equilvalent.
co2_clean['OBS_VALUE'] = co2_clean['OBS_VALUE'] * 1000
co2_clean.to_csv('co2.csv', index = False)

## GTFP's All Variables Append

In [24]:
# In this step, we will append all the 6 GTFP variables:
gtfp_vars = pd.concat([appended_clean, co2_clean])
gtfp_vars

,country_code,country,Economic activity,Measure,year,OBS_VALUE
0,GBR,United Kingdom,"Agriculture, forestry and fishing",Total employment,2016,396.312
1,GBR,United Kingdom,Manufacturing,Total employment,2016,2495.132
2,USA,United States,"Agriculture, forestry and fishing",Total employment,2016,2269.000
3,USA,United States,Manufacturing,Total employment,2016,12646.000
4,SVN,Slovenia,"Agriculture, forestry and fishing",Total employment,2000,106.700
...,...,...,...,...,...,...
1318,USA,United States,Services,co2,2016,3967528.000
1319,USA,United States,Services,co2,2017,4068730.000
1320,USA,United States,Services,co2,2018,4187182.000
1321,USA,United States,Services,co2,2019,4076490.000
1322,USA,United States,Services,co2,2020,3620839.000

In [25]:
# In this step, we will append all the 6 GTFP variables:
gtfp_vars = pd.concat([appended_clean, co2_clean])
gtfp_vars

# Next, we transform this dataframe to a wide format for further Stata calculation:
gtfp_vars2 = gtfp_vars.pivot_table(index = ['country_code', 'country', 'year', 'Economic activity'], columns = 'Measure', values = 'OBS_VALUE').reset_index()

# We rename these columns a little bit:
gtfp_vars_clean = gtfp_vars2.rename(columns = {'Economic activity': 'industry',
                                          'Intermediate consumption': 'ic',
                                          'Net capital stock': 'k',
                                          'Net capital stock, ICT equipment, software and databases': 'ict',
                                          'Total employment': 'l',
                                          'Value added': 'va'})

gtfp_vars_clean

Measure,country_code,country,year,industry,ic,k,ict,l,va,co2
0,AUT,Austria,2000,"Agriculture, forestry and fishing",6.190985e+03,3.732342e+04,8.822515e+01,230.748,5.827303e+03,13340.0
1,AUT,Austria,2000,Manufacturing,1.028941e+05,9.955717e+04,3.477230e+03,653.653,6.530993e+04,99104.0
2,AUT,Austria,2000,Services,1.324217e+05,9.001127e+05,3.236673e+04,2539.177,2.053981e+05,51593.0
3,AUT,Austria,2001,"Agriculture, forestry and fishing",6.337063e+03,3.678494e+04,9.122894e+01,229.597,6.036056e+03,13398.0
4,AUT,Austria,2001,Manufacturing,1.081827e+05,1.015607e+05,3.853052e+03,654.362,6.666408e+04,100074.0
...,...,...,...,...,...,...,...,...,...,...
1318,USA,United States,2019,Manufacturing,3.471142e+06,4.050044e+06,9.267077e+04,13104.000,2.212804e+06,3323651.0
1319,USA,United States,2019,Services,1.024152e+07,5.147098e+07,1.602809e+06,140108.000,1.544458e+07,4076490.0
1320,USA,United States,2020,"Agriculture, forestry and fishing",2.659937e+05,6.649042e+05,7.693950e+02,2135.000,1.644452e+05,930991.0
1321,USA,United States,2020,Manufacturing,3.074722e+06,4.185736e+06,9.137605e+04,12652.000,2.070151e+06,2937810.0
1322,USA,United States,2020,Services,9.792720e+06,5.337488e+07,1.665384e+06,132206.000,1.525638e+07,3620839.0

## Exporting Clean Data For Stata's GTFP Calculation

In [26]:
# We divide the data above into 3 dataframes for individual industries:
agri = gtfp_vars_clean[gtfp_vars_clean['industry'].str.contains('Agri')]
ser = gtfp_vars_clean[gtfp_vars_clean['industry'].str.contains('Ser')]
manu = gtfp_vars_clean[gtfp_vars_clean['industry'].str.contains('Manu')]

In [27]:
# We export to 3 csv files:
agri.to_csv('agri_clean.csv')
ser.to_csv('ser_clean.csv')
manu.to_csv('manu_clean.csv')

In [28]:
# We also export the gtfp_vars_clean dataset:
gtfp_vars_clean = gtfp_vars_clean[['country_code',	'country',	'industry', 'year'		,'ic',	'k',	'ict', 'va',	 'l', 'co2']]
gtfp_vars_clean = gtfp_vars_clean.rename(columns = {'country_code': 'ref_area',
                                  'country':'referencearea',
                                  'industry':'economicactivity',
                                  'co2':'co2_emission'})
gtfp_vars_clean.to_csv('OECD_input_output.csv', index = False)

## Making Data Description Table

### Making 'Statistical Description' Table

In [29]:
# Let's take another quick look at our gtfp variables dataframe:
gtfp_vars_clean.head()

Measure,ref_area,referencearea,economicactivity,year,ic,k,ict,va,l,co2_emission
0,AUT,Austria,"Agriculture, forestry and fishing",2000,6190.985171,37323.421887,88.225147,5827.303400,230.748,13340.0
1,AUT,Austria,Manufacturing,2000,102894.082624,99557.166669,3477.229978,65309.929396,653.653,99104.0
2,AUT,Austria,Services,2000,132421.708747,900112.743165,32366.727011,205398.115833,2539.177,51593.0
3,AUT,Austria,"Agriculture, forestry and fishing",2001,6337.062986,36784.937935,91.228939,6036.055946,229.597,13398.0
4,AUT,Austria,Manufacturing,2001,108182.718601,101560.695465,3853.051706,66664.084940,654.362,100074.0

In [30]:
# In this research, we only use the variable K for GTFP calculation.
# To compare the effect of ICT capital and non-ICT capital, we need to create the 'non-ict K' variable:
gtfp_vars_clean['non_ict_k'] = gtfp_vars_clean['k'] - gtfp_vars_clean['ict']
gtfp_vars_clean.head()

Measure,ref_area,referencearea,economicactivity,year,ic,k,ict,va,l,co2_emission,non_ict_k
0,AUT,Austria,"Agriculture, forestry and fishing",2000,6190.985171,37323.421887,88.225147,5827.303400,230.748,13340.0,37235.196740
1,AUT,Austria,Manufacturing,2000,102894.082624,99557.166669,3477.229978,65309.929396,653.653,99104.0,96079.936691
2,AUT,Austria,Services,2000,132421.708747,900112.743165,32366.727011,205398.115833,2539.177,51593.0,867746.016155
3,AUT,Austria,"Agriculture, forestry and fishing",2001,6337.062986,36784.937935,91.228939,6036.055946,229.597,13398.0,36693.708997
4,AUT,Austria,Manufacturing,2001,108182.718601,101560.695465,3853.051706,66664.084940,654.362,100074.0,97707.643758

In [31]:
# We want our 'Statistical Description' table to be formatted as follow:
# 7 columns: Sector, Variables, Mean, Median, Std, Max, Min
# To do that, the idea is to first unpivot the 'gtfp_vars_clean' table and use the 'groupby()' function.

# Step 1: unpivot the table:
gtfp_unpivot = gtfp_vars_clean.melt(id_vars = {'ref_area', 'referencearea', 'economicactivity', 'year'}, var_name = 'variables', value_name = 'value')
# We remove the 'k' variable because we don't need it anymore.
gtfp_unpivot = gtfp_unpivot[gtfp_unpivot['variables'] != 'k']

# Step 2: aggregate the table to get the expected results.
gtfp_unpivot = gtfp_unpivot.groupby(['economicactivity', 'variables'])['value'].agg(['mean', 'median', 'std', 'max', 'min']).reset_index().round(2)
gtfp_unpivot

,economicactivity,variables,mean,median,std,max,min
0,"Agriculture, forestry and fishing",co2_emission,75801.61,16985.00,196855.01,994888.00,940.00
1,"Agriculture, forestry and fishing",ic,27023.54,8349.95,52002.56,301274.89,240.26
2,"Agriculture, forestry and fishing",ict,294.43,116.46,597.23,5000.08,0.05
3,"Agriculture, forestry and fishing",l,469.36,134.97,767.27,3848.00,3.65
4,"Agriculture, forestry and fishing",non_ict_k,73399.61,23761.90,126643.95,664134.77,1167.99
5,"Agriculture, forestry and fishing",va,20698.85,5511.66,38495.40,228489.03,124.26
6,Manufacturing,co2_emission,441954.63,105582.00,922551.29,5294724.00,7189.00
7,Manufacturing,ic,451405.06,132221.52,834212.73,4094072.40,7477.63
8,Manufacturing,ict,16093.22,4072.88,31906.88,127527.53,36.77
9,Manufacturing,l,2033.73,539.00,3541.07,17612.00,31.80
10,Manufacturing,non_ict_k,392104.65,112017.00,838300.35,4094360.15,5517.45
11,Manufacturing,va,224715.56,64466.45,462928.65,2216779.85,2477.56
12,Services,co2_emission,349989.72,67662.00,868346.25,4417252.00,8811.00
13,Services,ic,763698.84,173693.00,1724368.56,10241519.04,13026.43
14,Services,ict,114712.80,16706.92,276596.23,1665383.72,688.68
15,Services,l,13454.72,3071.28,27698.11,140108.00,192.75
16,Services,non_ict_k,3837643.31,796605.38,8939904.55,51709493.08,61211.47
17,Services,va,1177303.21,215953.54,2730220.11,15444575.95,14197.01